[supervisord]
nodaemon=true
logfile=/var/www/storage/logs/supervisor/supervisord.log
pidfile=/var/www/storage/logs/supervisor/supervisord.pid


[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=jinesh
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/worker.log
stopwaitsecs=3600
